services:
  postgres:
    image: postgres:16
    container_name: hexmaster_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  hexmaster_bot:
    build: .
    container_name: hexmaster_bot
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OCR_URL=${OCR_URL}
    volumes:
      - shared_data:/app/shared
    network_mode: host

volumes:
  pgdata:
  shared_data:
